### ISSUE TITLE
Revise READ.ME to specify Type III SS in multiple regression without interaction

### ISSUE THREAD

**Issue by jimstigler** [UCLATALL/supernova#13]
@adamblake  Doesn't our multiple regression without interactions also use Type III SS? If so we should add after parentheses like in the next section. Maybe should cite JMR for how we are calculating SS and PREs.

**Comment by adamblake** [comment]
Yes --- that's correct.  In fact, all of them are Type III, there's just no difference between the types in the 1 and 0 predictor models. I'll include the type indication like in the other heading and add a paragraph at the top about how the values are calculated using the model comparison approach.

**Comment by jimstigler** [comment]
I think you only need to add the Type III designation to multiple
regression (without interactions)... it doesn't make sense for 1 and 0
predictors.
