### ISSUE TITLE
generate_models() doesn't print well

### ISSUE THREAD

**Issue by jiyunson** [UCLATALL/supernova#34]
As I'm exploring the other features/functions of supernova, I appreciate you even more @adamblake!

The generate_models() function doesn't seem to print well unless I put `print(generate_models(my_model))`. If I don't, I get something like this (both in our CourseKata jupyterhub and in deepnote)

![image](https://user-images.githubusercontent.com/30084828/150658464-324d45a9-594b-43a3-a5d4-55f1b03e7799.png)

**Comment by adamblake** [comment]
Thanks, @jiyunson! I'll check on the print settings to make sure this works for
- R console (and ckcode)
- R markdown
- Jupyter Notebooks (and Deepnote)
